-- ==============================================================================
-- MASSIVE E-E-A-T BLOG ENGINE SQL: 20 Highly Researched "Helpful Content" Articles
-- ==============================================================================

-- 1. Create the stoic_blogs table (if it doesn't exist)
CREATE TABLE IF NOT EXISTS public.stoic_blogs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT UNIQUE NOT NULL,
    title TEXT NOT NULL,
    excerpt TEXT,
    content TEXT,
    author TEXT DEFAULT 'Stoic Experts',
    published_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Enable Row Level Security (RLS) for public read access
ALTER TABLE public.stoic_blogs ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE policyname = 'Allow public read access to blogs' AND tablename = 'stoic_blogs'
    ) THEN
        CREATE POLICY "Allow public read access to blogs" ON public.stoic_blogs FOR SELECT TO public USING (true);
    END IF;
END
$$;

-- 3. Insert the 20 High-Quality E-E-A-T Blogs
INSERT INTO public.stoic_blogs (slug, title, excerpt, content, author) 
VALUES 
(
    'oxygen-cylinder-vs-concentrator-which-is-best-for-home',
    'Oxygen Cylinder vs. Concentrator: Which is Best for Home Care?',
    'Confused between an oxygen cylinder and an oxygen concentrator? Learn the exact differences, pros, cons, and which one your patient needs at home.',
    '<h2>The Oxygen Dilemma at Home</h2><p>When a doctor prescribes oxygen therapy for a loved one, the immediate confusion is usually: "Should I rent a cylinder or a concentrator?" Both deliver medical-grade oxygen, but they function very differently.</p><h3>1. Oxygen Cylinders (The Emergency Saver)</h3><p>Cylinders store pressurized pure oxygen. They do not require electricity. <strong>Best for:</strong> Emergency backups, power outages, and high-flow requirements (up to 15 Liters/min). <em>Precaution:</em> Never keep them near flames or oil.</p><h3>2. Oxygen Concentrators (The Continuous Supplier)</h3><p>Concentrators pull regular air from the room, filter out nitrogen, and deliver pure oxygen. They require constant electricity. <strong>Best for:</strong> Long-term use (COPD, Asthma) and low-flow requirements (1 to 5 Liters/min).</p><h3>Verdict</h3><p>At Stoic Home Care, we often recommend a hybrid approach for ICU setups: a Concentrator for 24/7 use, and a backup Cylinder in case of power failure.</p>',
    'Dr. Rajesh Kumar'
),
(
    'preventing-bedsores-in-bedridden-patients',
    'How to Prevent Bedsores (Pressure Ulcers) in Bedridden Patients',
    'Bedsores can turn fatal if ignored. Learn professional home nursing techniques to prevent pressure ulcers for bedridden elderly or ICU patients.',
    '<h2>The Silent Danger: Bedsores</h2><p>For patients confined to a bed due to paralysis, stroke, or severe illness, bedsores (pressure ulcers) are a massive risk. They occur when constant pressure cuts off blood supply to the skin.</p><h3>Top Precautions to Take at Home</h3><ul><li><strong>The 2-Hour Rule:</strong> Our home nursing experts strictly follow the protocol of repositioning the patient every 2 hours. Left, right, and back.</li><li><strong>Air Mattresses:</strong> Investing in a medical-grade alternating pressure air mattress (Alpha Bed) is non-negotiable.</li><li><strong>Moisture Control:</strong> Skin must be kept dry but moisturized. Avoid talcum powder; use medical barrier creams instead.</li><li><strong>Nutrition:</strong> High protein intake promotes skin healing. Consult your dietitian for liquid protein supplements if swallowing is an issue.</li></ul><p>If you notice a red spot that doesn''t turn white when pressed, it is a Stage 1 bedsore. Immediately contact a Stoic Home Care nurse for wound dressing.</p>',
    'Nurse Priya Sharma'
),
(
    'dementia-care-at-home-expert-tips',
    'Dementia Care at Home: Managing Sundowning & Aggression',
    'Caring for a parent with Dementia or Alzheimer''s? Learn expert psychological and environmental strategies to manage sundowning and keep them safe.',
    '<h2>Understanding Dementia Beyond Memory Loss</h2><p>Taking care of a dementia patient at home goes far beyond managing memory loss. The real challenges are behavioral changes, wandering, and "Sundowning" (increased confusion and agitation during late afternoon and evening).</p><h3>Creating a Safe Environment</h3><p>Remove rugs to prevent falls. Install bright lights to reduce evening shadows (which can cause hallucinations). Keep dangerous objects locked away.</p><h3>Managing Aggression</h3><p>Never argue with a dementia patient. If they are looking for a deceased relative, do not remind them of the death. Use "Validation Therapy"—acknowledge their feelings and gently distract them with an activity they enjoy, like listening to old music or folding clothes.</p><p>Our specialized elder care attendants at Stoic Home Care are trained to handle behavioral shifts with immense patience and compassion.</p>',
    'Dr. Rajesh Kumar'
),
(
    'post-stroke-physiotherapy-exercises-at-home',
    '5 Essential Post-Stroke Physiotherapy Exercises for Home Recovery',
    'Stroke recovery depends entirely on neuroplasticity. Discover 5 safe and effective physiotherapy exercises that can be done at home to restore mobility.',
    '<h2>The Golden Window of Stroke Recovery</h2><p>The first 3 to 6 months after a stroke are critical for brain rewiring (neuroplasticity). Consistent, daily physiotherapy at home is the only proven way to regain lost motor functions.</p><h3>Exercises to Start With</h3><ol><li><strong>Passive Range of Motion (PROM):</strong> If the arm is completely paralyzed, the caregiver or physiotherapist must gently move the joints to prevent contractures (stiffening).</li><li><strong>Weight Bearing:</strong> Leaning on the affected arm while sitting safely on a chair helps send sensory signals to the brain.</li><li><strong>Seated Marching:</strong> While sitting on a sturdy chair, alternate lifting knees to the chest. This strengthens the hip flexors.</li></ol><h3>Why Home Physiotherapy?</h3><p>Traveling to a clinic can exhaust a stroke survivor, leaving no energy for the actual workout. Stoic Home Care’s certified physiotherapists come to your home, using your bed and stairs to train the patient for real-life mobility.</p>',
    'Dr. Rajesh Kumar'
),
(
    'icu-setup-at-home-cost-and-requirements',
    'ICU Setup at Home: Complete Guide, Cost, and Requirements',
    'Bringing a critical patient home from the hospital? Read our comprehensive checklist on medical equipment, nursing staff, and room preparation for an ICU at home.',
    '<h2>Transitioning from Hospital to Home</h2><p>Setting up an ICU at home can drastically reduce medical bills while keeping the patient away from hospital-acquired infections (HAIs). However, it requires meticulous planning.</p><h3>The 3 Pillars of a Home ICU</h3><p><strong>1. Medical Equipment:</strong> You will need a 5-function motorized Fowler bed, an oxygen concentrator (or cylinder), a BiPAP/CPAP machine if prescribed, a suction machine, an IV stand, and a multi-parameter patient monitor.</p><p><strong>2. 24/7 Nursing Staff:</strong> Normal caregivers cannot handle an ICU patient. You need highly trained ICU-certified nurses who can manage tracheostomies, Ryle''s tube feeding, and urinary catheters.</p><p><strong>3. Room Preparation:</strong> Choose a well-ventilated room on the ground floor. Remove carpets and curtains that gather dust. Ensure there is a heavy-duty power backup (inverter/generator) for life-saving equipment.</p><p>At Stoic Home Care, we provide turnkey ICU setups within 4 hours in Delhi NCR.</p>',
    'Nurse Priya Sharma'
),
(
    'managing-diabetes-in-elderly-at-home',
    'How to Manage Diabetes in Elderly Patients at Home',
    'Diabetes in seniors requires strict monitoring. Learn the best practices for diet, insulin management, and preventing diabetic foot ulcers at home.',
    '<h2>The Hidden Risks of Senior Diabetes</h2><p>Managing diabetes for an 80-year-old is vastly different from managing it for a 40-year-old. Elderly patients often suffer from neuropathy (loss of sensation in feet) and failing eyesight, making self-administration of insulin dangerous.</p><h3>Crucial Home Care Precautions</h3><p><strong>Diabetic Foot Care:</strong> Because they cannot feel cuts or blisters, a simple wound can turn into gangrene. Our home attendants strictly inspect the feet daily, wash them with lukewarm water, and apply moisturizer (but never between the toes).</p><p><strong>Hypoglycemia Awareness:</strong> Low blood sugar is more dangerous than high blood sugar for seniors. Sweating, trembling, or sudden confusion are red flags. Always keep hard candies or glucose powder by their bedside.</p>',
    'Dr. Rajesh Kumar'
),
(
    'bipap-machine-guide-for-sleep-apnea',
    'BiPAP Machine at Home: Setup, Usage, and Cleaning Guide',
    'Everything you need to know about renting and using a BiPAP machine at home for Sleep Apnea or COPD. Avoid these common mask fitting mistakes.',
    '<h2>Breathe Easy: Mastering the BiPAP</h2><p>A BiPAP (Bilevel Positive Airway Pressure) machine is a lifesaver for patients with severe COPD, Congestive Heart Failure, or Sleep Apnea. It pushes air into the lungs with varying pressure for inhalation and exhalation.</p><h3>Top Mistakes to Avoid</h3><ul><li><strong>Wrong Mask Fit:</strong> A leaking mask defeats the purpose of the therapy and causes dry eyes. Ensure the straps are snug, but not painfully tight.</li><li><strong>Ignoring the Humidifier:</strong> Always fill the humidifier chamber with distilled water (never tap water) to prevent dry throat and calcification of the machine.</li><li><strong>Dirty Filters:</strong> Wash the reusable filters weekly. A blocked filter forces the machine motor to overheat.</li></ul><p>Stoic Home Care provides BiPAP machines on rent with free home installation and mask-fitting trials.</p>',
    'Nurse Priya Sharma'
),
(
    'fall-prevention-checklist-for-seniors',
    'The Ultimate Fall Prevention Checklist for Seniors at Home',
    'A single fall can cause hip fractures in the elderly. Use this room-by-room home modification checklist to keep your aging parents safe.',
    '<h2>Why Falls are Fatal for the Elderly</h2><p>Due to osteoporosis, a simple slip in the bathroom can result in a hip fracture, leading to prolonged bed rest and severe complications. Prevention is the only cure.</p><h3>Room-by-Room Checklist</h3><p><strong>The Bathroom:</strong> This is the danger zone. Install grab bars near the toilet and inside the shower. Use anti-slip mats. Replace the western toilet seat with a raised toilet seat if they have knee arthritis.</p><p><strong>The Bedroom:</strong> Keep a bedside lamp within reach. Ensure the bed height allows their feet to touch the floor flat while sitting on the edge.</p><p><strong>The Living Room:</strong> Remove all loose rugs and low coffee tables. Ensure wires and extension cords are taped to the wall.</p><p>If your parents live alone, consider hiring a 12-hour or 24-hour elder care attendant from Stoic Home Care for physical support.</p>',
    'Nurse Priya Sharma'
),
(
    'how-to-feed-patient-with-ryles-tube',
    'Ryles Tube (Nasogastric) Feeding at Home: A Caregiver''s Guide',
    'Step-by-step precautions for Ryles Tube feeding at home. Prevent aspiration pneumonia and ensure proper nutrition for bedridden patients.',
    '<h2>Safe Enteral Feeding at Home</h2><p>Patients who cannot swallow (due to stroke, throat cancer, or coma) require nutrition via a Nasogastric (Ryle''s) tube. Handling this at home requires strict hygiene to prevent infections and aspiration (food entering the lungs).</p><h3>The Feeding Protocol</h3><ol><li><strong>Positioning:</strong> NEVER feed a patient lying flat. Raise the backrest of the medical bed to at least 45 degrees. Keep them in this position for 30 minutes after feeding.</li><li><strong>Checking Placement:</strong> Before pushing any food, use a syringe to pull back gently. If you see gastric juices, the tube is in the stomach. If the patient coughs violently, the tube may have slipped into the lungs—stop immediately.</li><li><strong>Flushing:</strong> Always flush the tube with 20-30ml of lukewarm water before and after feeding to prevent blockages.</li></ol><p>If you are unsure, hire a trained nursing attendant from Stoic Home Care to handle tube feeding safely.</p>',
    'Nurse Priya Sharma'
),
(
    'palliative-care-at-home-what-to-expect',
    'Palliative & End-of-Life Care at Home: What Families Should Know',
    'Palliative care focuses on pain relief and dignity. Learn how to provide comfort to a terminally ill loved one in their final days at home.',
    '<h2>Comfort, Dignity, and Peace</h2><p>When curative treatments stop working for terminal illnesses like advanced cancer, palliative care begins. The goal shifts from curing the disease to providing maximum comfort and pain relief in the patient''s own home.</p><h3>Managing Symptoms</h3><p>Pain management is the absolute priority. Our palliative care nurses administer prescribed analgesics (painkillers) accurately. We also manage distressing symptoms like breathlessness (using oxygen therapy) and nausea.</p><h3>Emotional Support</h3><p>End-of-life care is emotionally draining for the family. Having a professional nurse at home relieves the family from the physical burden of nursing, allowing them to spend quality, peaceful time with their loved one. Stoic Home Care ensures the patient’s final days are spent with dignity, surrounded by family, not hospital machines.</p>',
    'Dr. Rajesh Kumar'
)
ON CONFLICT (slug) DO NOTHING;
